name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      # Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        working-directory: backend
        run: |
          pytest tests

      # Build Docker image
      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t super-soccer-showdown .

      # # Log in to AWS ECR
      # - name: Log in to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v1
      #   with:
      #     region: ${{ secrets.AWS_REGION }}

      # # Tag Docker image
      # - name: Tag Docker image
      #   working-directory: backend
      #   run: |
      #     docker tag super-soccer-showdown:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-ecr-repository:latest

      # # Push Docker image to ECR
      # - name: Push Docker image
      #   working-directory: backend
      #   run: |
      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-ecr-repository:latest
